### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by z2wrx** [srivastavaprashant/mgarch#1]
pip3 install mgarch

    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/95/mcc3f9857xn75vy4y9kdjhrh0000gn/T/pip-install-ylu895gc/mgarch/setup.py", line 32
        )\
         ^
    SyntaxError: unexpected EOF while parsing

**Comment by srivastavaprashant** [comment]
fixed
